{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StrictData #-}

module Agda2Lean.Lean.Emit
  ( DiagnosticSeverity (..)
  , BuiltinReceipt (..)
  , EmitOptions (..)
  , LeanDiagnostic (..)
  , LeanOutput (..)
  , defaultEmitOptions
  , emitLeanModule
  , renderDiagnostics
  , renderBuiltinReceipts
  ) where

import Agda2Lean.IR
import Agda2Lean.Platform
import Control.Monad.Reader
import Control.Monad.State.Strict
import Data.Char (isAlpha, isAlphaNum)
import Data.List (find, sortOn)
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Set (Set)
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as Text
import qualified Data.Vector as Vector

data EmitOptions = EmitOptions
  { emitNamespace :: Bool
  , emitSorryBodies :: Bool
  , emitRegistry :: Map BuiltinId PlatformMapping
  }
  deriving stock (Eq, Show)

defaultEmitOptions :: EmitOptions
defaultEmitOptions =
  EmitOptions
    { emitNamespace = True
    , emitSorryBodies = False
    , emitRegistry = platformMappings
    }

data DiagnosticSeverity = Info | Warning | Error
  deriving stock (Bounded, Enum, Eq, Ord, Show)

data LeanDiagnostic = LeanDiagnostic
  { diagnosticSeverity :: DiagnosticSeverity
  , diagnosticCode :: Text
  , diagnosticDeclaration :: Maybe CanonicalName
  , diagnosticMessage :: Text
  }
  deriving stock (Eq, Show)

data BuiltinReceipt = BuiltinReceipt
  { builtinReceiptDeclaration :: CanonicalName
  , builtinReceiptAgdaBinding :: Text
  , builtinReceiptId :: BuiltinId
  , builtinReceiptRegistryVersion :: Text
  , builtinReceiptRule :: Maybe Text
  , builtinReceiptLeanTarget :: Maybe Text
  , builtinReceiptComputation :: Maybe ComputationTreatment
  , builtinReceiptArgumentPolicy :: Maybe ArgumentPolicy
  , builtinReceiptAxiomDelta :: Vector.Vector Text
  , builtinReceiptStatus :: Text
  }
  deriving stock (Eq, Show)

data LeanOutput = LeanOutput
  { leanSource :: Text
  , leanDiagnostics :: Vector.Vector LeanDiagnostic
  , leanBuiltinReceipts :: Vector.Vector BuiltinReceipt
  }
  deriving stock (Eq, Show)

data RenderEnv = RenderEnv
  { renderTerms :: Map TermId CoreTerm
  , renderBinders :: Map BinderId Text
  , renderRegistry :: Map BuiltinId PlatformMapping
  , renderNameOverrides :: Map CanonicalName Text
  }

type RenderM = ReaderT RenderEnv (State (Set TermId))

emitLeanModule :: EmitOptions -> ModuleIR -> LeanOutput
emitLeanModule options moduleIR =
  LeanOutput
    { leanSource =
        Text.unlines
          ( headerLines
              <> importLines
              <> optionLines
              <> universeLines
              <> namespaceOpen
              <> concat declarationBlocks
              <> natTail
              <> namespaceClose
          )
    , leanDiagnostics = Vector.fromList (concat diagnostics)
    , leanBuiltinReceipts = Vector.fromList (concat receipts)
    }
  where
    headerLines =
      [ "-- Generated by agda2lean. Edits will be overwritten."
      , "-- Source module: " <> unCanonicalName (moduleName moduleIR)
      , ""
      ]
    importLines =
      [ "import " <> leanQualifiedName imported
      | imported <- Set.toAscList (moduleImports moduleIR)
      ]
        <> ["" | not (Set.null (moduleImports moduleIR))]
    optionLines =
      [ "set_option autoImplicit false"
      , ""
      ]
    namespaceOpen =
      if emitNamespace options
        then ["namespace " <> leanQualifiedName (moduleName moduleIR), ""]
        else []
    universeLines =
      case Set.toAscList (moduleUniverseNames moduleIR) of
        [] -> []
        names -> ["universe " <> Text.unwords (map leanNamePart names), ""]
    namespaceClose =
      if emitNamespace options
        then ["end " <> leanQualifiedName (moduleName moduleIR)]
        else []
    rendered =
      map
        (emitDeclaration options moduleIR)
        (Vector.toList (moduleDeclarations moduleIR))
    declarationBlocks = map (\(blocks, _, _) -> blocks) rendered
    diagnostics = map (\(_, ds, _) -> ds) rendered
    receipts = map (\(_, _, rs) -> rs) rendered
    natTail =
      if moduleName moduleIR == CanonicalName "Agda.Builtin.Nat"
        then
          [ "noncomputable instance (n : _root_.Nat) : OfNat Nat n := ⟨Nat.zero⟩"
          , ""
          ]
        else []

emitDeclaration ::
  EmitOptions ->
  ModuleIR ->
  CoreDeclaration ->
  ([Text], [LeanDiagnostic], [BuiltinReceipt])
emitDeclaration options moduleIR declaration =
  case declarationBuiltin declaration of
    Just builtin -> emitBuiltinDeclaration builtin declaration
    Nothing ->
      case renderRoot options moduleIR (declarationType declaration) of
        Left message ->
          ( metadata
              <> [ "-- BLOCKED: the Agda statement could not be represented faithfully."
                 , "-- " <> message
                 , ""
                 ]
          , [diagnostic Error "A2L-E-TYPE" message]
          , []
          )
        Right renderedType ->
          let (bodyLines, bodyDiagnostics) = emitBody renderedType
           in (metadata <> bodyLines <> [""], bodyDiagnostics, [])
  where
    name = localLeanName (moduleName moduleIR) (declarationName declaration)
    metadata =
      [ "-- Agda: " <> unCanonicalName (declarationName declaration)
      , "-- Source: "
          <> sourceFile (declarationSource declaration)
          <> ":"
          <> Text.pack (show (sourceStartLine (declarationSource declaration)))
      , "-- Direct dependencies: " <> renderDependencies (declarationDependencies declaration)
      , "-- Mapping: " <> Text.pack (show (declarationMapping declaration))
      ]

    diagnostic severity code message =
      LeanDiagnostic
        { diagnosticSeverity = severity
        , diagnosticCode = code
        , diagnosticDeclaration = Just (declarationName declaration)
        , diagnosticMessage = message
        }

    emitBuiltinDeclaration builtin currentDeclaration =
      let receipt = builtinReceipt builtin
       in
      case builtin of
        BuiltinEquality ->
          ( [ "def «_≡_» {α : Type} (x y : α) : Prop := Eq x y"
            , ""
            ]
          , []
          , [receipt]
          )
        BuiltinRefl ->
          ( [ "theorem «_≡_».refl {α : Type} {x : α} : «_≡_» x x := rfl"
            , ""
            ]
          , []
          , [receipt]
          )
        BuiltinNat -> native receipt "abbrev" "_root_.Nat"
        BuiltinNatZero -> native receipt "def" "_root_.Nat.zero"
        BuiltinNatSuc -> native receipt "def" "_root_.Nat.succ"
        BuiltinNatAdd -> native receipt "def" "_root_.Nat.add"
        BuiltinNatSub -> native receipt "def" "_root_.Nat.sub"
        BuiltinNatMul -> native receipt "def" "_root_.Nat.mul"
        BuiltinNatEq -> native receipt "def" "fun (x : Nat) (y : Nat) => decide (x = y)"
        BuiltinNatLt -> native receipt "def" "fun (x : Nat) (y : Nat) => decide (x < y)"
        BuiltinBool -> native receipt "abbrev" "_root_.Bool"
        BuiltinBoolTrue -> native receipt "def" "_root_.Bool.true"
        BuiltinBoolFalse -> native receipt "def" "_root_.Bool.false"
        BuiltinList ->
          nativeLines receipt
            [ "abbrev " <> builtinLocalName <> ".{u} (α : Type u) := _root_.List α" ]
        BuiltinListNil ->
          nativeLines receipt
            [ "def " <> builtinLocalName <> ".{u} {α : Type u} : List α := _root_.List.nil" ]
        BuiltinListCons ->
          nativeLines receipt
            [ "def "
                <> builtinLocalName
                <> ".{u} {α : Type u} (x : α) (xs : List α) : List α := _root_.List.cons x xs"
            ]
        BuiltinLevel -> native receipt "abbrev" "Type"
        _ ->
          ( metadata
              <> [ "-- BLOCKED: builtin has no declaration lowering yet."
                 , "-- " <> builtinAuditName builtin
                 , ""
                 ]
                 , [diagnostic Error "A2L-E-BUILTIN" "registered builtin has no declaration lowering"]
                 , [receipt {builtinReceiptStatus = "blocked"}]
          )
      where
        builtinLocalName =
          localLeanName (moduleName moduleIR) (declarationName currentDeclaration)

        nativeLines nativeReceipt lines' =
          (lines' <> [""], [], [nativeReceipt])

        native nativeReceipt keyword target =
          ( [ keyword
                <> " "
                <> localLeanName (moduleName moduleIR) (declarationName currentDeclaration)
                <> " := "
                <> target
            , ""
            ]
          , []
          , [nativeReceipt {builtinReceiptLeanTarget = Just target}]
          )

    builtinReceipt builtin =
      case Map.lookup builtin (emitRegistry options) of
        Nothing ->
          BuiltinReceipt
            { builtinReceiptDeclaration = declarationName declaration
            , builtinReceiptAgdaBinding = builtinAuditName builtin
            , builtinReceiptId = builtin
            , builtinReceiptRegistryVersion = platformRegistryVersion
            , builtinReceiptRule = Nothing
            , builtinReceiptLeanTarget = Nothing
            , builtinReceiptComputation = Nothing
            , builtinReceiptArgumentPolicy = Nothing
            , builtinReceiptAxiomDelta = Vector.empty
            , builtinReceiptStatus = "unregistered"
            }
        Just mapping ->
          BuiltinReceipt
            { builtinReceiptDeclaration = declarationName declaration
            , builtinReceiptAgdaBinding = platformAuditName mapping
            , builtinReceiptId = builtin
            , builtinReceiptRegistryVersion = platformRegistryVersion
            , builtinReceiptRule = Just (platformMode mapping)
            , builtinReceiptLeanTarget = Just (platformTarget mapping)
            , builtinReceiptComputation = Just (platformComputation mapping)
            , builtinReceiptArgumentPolicy = Just (platformArgumentPolicy mapping)
            , builtinReceiptAxiomDelta = Vector.fromList (platformAxiomDelta mapping)
            , builtinReceiptStatus = "mapped"
            }

    emitBody renderedType =
      let renderedType' =
            if declarationName declaration == CanonicalName "Agda.Primitive.Level"
              then "Type (0 + 1)"
              else renderedType
       in emitDefinition renderedType' (declarationDefinition declaration)

    emitDefinition renderedType definition =
      case definition of
        TermDefinition body ->
          emitTermDefinition renderedType body
        ClauseDefinition clauses ->
          emitClauseDefinition renderedType clauses
        RecordDefinition schema ->
          emitRecordDefinition renderedType schema
        DataDefinition schema ->
          emitDataDefinition renderedType schema
        ConstructorDefinition schema ->
          ( [ "-- Constructor is emitted by "
                <> unCanonicalName (constructorOwner schema)
                <> "."
            ]
          , []
          )
        ProjectionDefinition schema ->
          ( [ "-- Projection is emitted as field "
                <> unCanonicalName (projectionField schema)
                <> " of "
                <> unCanonicalName (projectionRecord schema)
                <> "."
            ]
          , []
          )
        AxiomDefinition
          | declarationRole declaration == AxiomDeclaration ->
              (["axiom " <> name <> " : " <> renderedType], [])
          | otherwise ->
              hardBlocked "non-axiom declaration has no portable definition"
        BlockedDefinition obligation ->
          hardBlocked (renderDefinitionObligation obligation)

    emitTermDefinition renderedType body
      | declarationMapping declaration > Encoded =
          blocked renderedType
            ( "mapping mode "
                <> Text.pack (show (declarationMapping declaration))
                <> " requires native Lean reconstruction"
            )
      | otherwise =
          case renderRoot options moduleIR body of
            Left reason -> blocked renderedType reason
            Right renderedBody ->
              ( [ declarationKeyword
                    <> " "
                    <> name
                    <> " : "
                    <> renderedType
                    <> " := "
                    <> renderedBody
                ]
              , []
              )

    emitClauseDefinition renderedType clauses
      | declarationMapping declaration > Encoded =
          blocked renderedType "clause definition requires native Lean reconstruction"
      | Vector.null clauses = hardBlocked "clause definition has no clauses"
      | otherwise =
          case traverse (renderClause options moduleIR) (Vector.toList clauses) of
            Left reason -> blocked renderedType reason
            Right renderedClauses ->
              ( (declarationKeyword <> " " <> name <> " : " <> renderedType)
                  : map ("  " <>) renderedClauses
              , []
              )

    emitRecordDefinition _renderedType schema =
      case renderRecordSchema options moduleIR name schema of
        Left reason -> blocked _renderedType reason
        Right lines' -> (lines', [])

    emitDataDefinition renderedType schema =
      case traverse renderConstructor (Vector.toList (dataConstructors schema)) of
        Left reason -> hardBlocked reason
        Right constructors ->
          ( ("inductive " <> name <> " : " <> renderedType <> " where")
              : map ("  " <>) constructors
          , []
          )
      where
        renderConstructor constructorName = do
          constructorDeclaration <-
            maybe
              (Left ("missing constructor declaration: " <> unCanonicalName constructorName))
              Right
              ( find
                  ((== constructorName) . declarationName)
                  (Vector.toList (moduleDeclarations moduleIR))
              )
          case declarationDefinition constructorDeclaration of
            ConstructorDefinition marker
              | constructorOwner marker == declarationName declaration -> do
                  constructorType <-
                    renderRoot options moduleIR (declarationType constructorDeclaration)
                  Right
                    ( "| "
                        <> leanNamePart (lastNamePart constructorName)
                        <> " : "
                        <> constructorType
                    )
              | otherwise ->
                  Left ("constructor owner mismatch: " <> unCanonicalName constructorName)
            _ -> Left ("declaration is not marked as a constructor: " <> unCanonicalName constructorName)

    declarationKeyword
      | isPropositionType moduleIR (declarationType declaration) = "theorem"
      | declarationRole declaration `elem` [Theorem, Certificate] = "theorem"
      | otherwise = "def"

    blocked renderedType reason
      | emitSorryBodies options =
          ( [ declarationKeyword <> " " <> name <> " : " <> renderedType <> " := by"
            , "  -- Explicit legacy reconstruction boundary: " <> reason
            , "  sorry"
            ]
          , [diagnostic Warning "A2L-W-RECONSTRUCT" reason]
          )
      | otherwise = hardBlocked reason

    hardBlocked reason =
      ( [ "-- BLOCKED " <> name
        , "-- " <> reason
        ]
      , [diagnostic Error "A2L-E-BODY" reason]
      )

renderDefinitionObligation :: DefinitionObligation -> Text
renderDefinitionObligation = \case
  UnsupportedDependentPattern reason -> "unsupported dependent pattern: " <> reason
  UnsupportedClauseBody reason -> "unsupported clause body: " <> reason
  UnsupportedDefinitionKind reason -> "unsupported definition kind: " <> reason

renderRoot :: EmitOptions -> ModuleIR -> TermId -> Either Text Text
renderRoot options moduleIR root =
  evalState
    ( runReaderT
        (renderTerm root)
        RenderEnv
          { renderTerms = moduleTerms moduleIR
          , renderBinders = Map.empty
          , renderRegistry = emitRegistry options
          , renderNameOverrides = moduleNameOverrides moduleIR
          }
    )
    Set.empty

renderTerm :: TermId -> RenderM (Either Text Text)
renderTerm termId = do
  active <- get
  if termId `Set.member` active
    then pure (Left ("cyclic term graph at " <> Text.pack (show termId)))
    else do
      table <- asks renderTerms
      case Map.lookup termId table of
        Nothing -> pure (Left ("missing term " <> Text.pack (show termId)))
        Just term -> do
          modify' (Set.insert termId)
          result <- renderCoreTerm term
          modify' (Set.delete termId)
          pure result

renderCoreTerm :: CoreTerm -> RenderM (Either Text Text)
renderCoreTerm = \case
  Var binderId -> do
    binders <- asks renderBinders
    pure
      ( maybe
          (Left ("unbound binder " <> Text.pack (show binderId)))
          Right
          (Map.lookup binderId binders)
      )
  Sort universe -> pure (Right (renderUniverse universe))
  Level level -> renderLevelExpr level
  Pi binder body -> renderBinderTerm "→" binder body
  Sigma binder body -> do
    renderedType <- renderTerm (binderType binder)
    renderedBody <- local (bindRenderedBinder binder) (renderTerm body)
    pure $ do
      type' <- renderedType
      body' <- renderedBody
      Right
        ( "Sigma (fun "
            <> leanBinderName binder
            <> " : "
            <> type'
            <> " => "
            <> body'
            <> ")"
        )
  Lam binder body -> do
    renderedType <- renderTerm (binderType binder)
    renderedBody <- local (bindRenderedBinder binder) (renderTerm body)
    pure $ do
      type' <- renderedType
      body' <- renderedBody
      Right
        ( "(fun "
            <> renderBinder binder type'
            <> " => "
            <> body'
            <> ")"
        )
  App function argument -> renderApplication function argument
  Constructor name arguments ->
    renderNamedApplication name arguments
  Eliminator name arguments -> do
    rendered <- mapM (renderTerm . argumentTerm) (Vector.toList arguments)
    overrides <- asks renderNameOverrides
    let target = Map.findWithDefault (leanQualifiedName name) name overrides
    pure $ do
      values <- sequence rendered
      case values of
        [receiver] -> Right ("(" <> target <> " " <> receiver <> ")")
        _ -> Right (parenthesizedApplication target values)
  Equality _ left right -> do
    renderedLeft <- renderTerm left
    renderedRight <- renderTerm right
    pure $ do
      left' <- renderedLeft
      right' <- renderedRight
      Right ("(" <> left' <> " = " <> right' <> ")")
  Axiom name -> do
    overrides <- asks renderNameOverrides
    pure (Right (Map.findWithDefault (renderConstant name) name overrides))
  Builtin builtin ->
    asks renderRegistry >>= \registry ->
      pure
        ( maybe
            (Left ("unregistered builtin: " <> Text.pack (show builtin)))
            (Right . platformTarget)
            (Map.lookup builtin registry)
        )
  Extension extension ->
    pure
      ( Left
          ("extension term requires lowering: " <> Text.pack (show extension))
      )

renderBinderTerm :: Text -> Binder -> TermId -> RenderM (Either Text Text)
renderBinderTerm arrow binder body = do
  renderedType <- renderTerm (binderType binder)
  renderedBody <- local (bindRenderedBinder binder) (renderTerm body)
  pure $ do
    type' <- renderedType
    body' <- renderedBody
    Right
      (renderBinder binder type' <> " " <> arrow <> " " <> body')

renderNamedApplication ::
  CanonicalName ->
  Vector.Vector Argument ->
  RenderM (Either Text Text)
renderNamedApplication name arguments = do
  rendered <- mapM (renderTerm . argumentTerm) (Vector.toList arguments)
  overrides <- asks renderNameOverrides
  let target = Map.findWithDefault (leanQualifiedName name) name overrides
  pure $ renderApplicationText target (Vector.toList arguments) <$> sequence rendered

renderApplication :: TermId -> Argument -> RenderM (Either Text Text)
renderApplication function finalArgument = do
  table <- asks renderTerms
  let (headId, arguments) = collectApplicationSpine table function [finalArgument]
  case Map.lookup headId table of
    Just (Builtin builtin) -> do
      registry <- asks renderRegistry
      case Map.lookup builtin registry of
        Nothing -> pure (Left ("unregistered builtin: " <> Text.pack (show builtin)))
        Just mapping -> renderProjectedApplication mapping arguments
    _ -> do
      renderedHead <- renderTerm headId
      renderedArguments <- mapM (renderTerm . argumentTerm) arguments
      pure $ do
        head' <- renderedHead
        arguments' <- sequence renderedArguments
        Right (renderApplicationText head' arguments arguments')

collectApplicationSpine :: Map TermId CoreTerm -> TermId -> [Argument] -> (TermId, [Argument])
collectApplicationSpine table current arguments =
  case Map.lookup current table of
    Just (App function argument) ->
      collectApplicationSpine table function (argument : arguments)
    _ -> (current, arguments)

renderProjectedApplication :: PlatformMapping -> [Argument] -> RenderM (Either Text Text)
renderProjectedApplication mapping sourceArguments =
  case projectArguments (platformArgumentPolicy mapping) sourceArguments of
    Left reason -> pure (Left reason)
    Right targetArguments -> do
      rendered <- mapM (renderTerm . argumentTerm) targetArguments
      pure $ do
        values <- sequence rendered
        Right (renderApplicationText (platformTarget mapping) targetArguments values)

projectArguments :: ArgumentPolicy -> [Argument] -> Either Text [Argument]
projectArguments PreserveArguments arguments = Right arguments
projectArguments (ProjectArguments sourceArity order) arguments
  | length arguments < required =
      Left
        ( "builtin application is under-applied: policy requires "
            <> Text.pack (show required)
            <> " source arguments, found "
            <> Text.pack (show (length arguments))
        )
  | otherwise =
      Right
        ( map (prefix !!) (map fromIntegral (Vector.toList order))
            <> suffix
        )
  where
    required = fromIntegral sourceArity
    (prefix, suffix) = splitAt required arguments

renderApplicationText :: Text -> [Argument] -> [Text] -> Text
renderApplicationText function arguments values =
  case values of
    [] -> function
    _
      | any ((/= Explicit) . argumentVisibility) arguments ->
          "(@" <> function <> " " <> Text.intercalate " " values <> ")"
      | otherwise ->
          "(" <> function <> " " <> Text.intercalate " " values <> ")"

bindRenderedBinder :: Binder -> RenderEnv -> RenderEnv
bindRenderedBinder binder environment =
  environment
    { renderBinders =
        Map.insert
          (binderId binder)
          (leanBinderName binder)
          (renderBinders environment)
    }

renderBinder :: Binder -> Text -> Text
renderBinder binder type' =
  case binderVisibility binder of
    Explicit -> "(" <> name <> " : " <> type' <> ")"
    Implicit -> "{" <> name <> " : " <> type' <> "}"
    Instance -> "[" <> name <> " : " <> type' <> "]"
  where
    name = leanBinderName binder

leanBinderName :: Binder -> Text
leanBinderName binder =
  let candidate = binderName binder
   in if Text.null candidate || candidate == "_"
        then "x" <> Text.pack (show (unBinderId (binderId binder)))
        else leanNamePart candidate

renderUniverse :: Universe -> Text
renderUniverse = \case
  UZero -> "Type"
  USuc universe -> "(Type (" <> renderLevel universe <> " + 1))"
  UMax universes -> "(Type " <> renderMaxLevel universes <> ")"
  ULevel name -> "(Type " <> leanNamePart name <> ")"
  UProp _ -> "Prop"
  USSet universe -> "(Type " <> renderLevel universe <> ")"

renderLevel :: Universe -> Text
renderLevel = \case
  UZero -> "0"
  USuc universe -> "(" <> renderLevel universe <> " + 1)"
  UMax universes -> renderMaxLevel universes
  ULevel name -> leanNamePart name
  UProp universe -> renderLevel universe
  USSet universe -> renderLevel universe

renderMaxLevel :: Vector.Vector Universe -> Text
renderMaxLevel universes =
  case map renderLevel (Vector.toList universes) of
    [] -> "0"
    level : levels -> foldl (\left right -> "(max " <> left <> " " <> right <> ")") level levels

renderLevelExpr :: LevelExpr -> RenderM (Either Text Text)
renderLevelExpr = \case
  LevelZero -> pure (Right "0")
  LevelSuccessor level ->
    fmap (fmap (\rendered -> "(" <> rendered <> " + 1)")) (renderLevelExpr level)
  LevelMaximum levels -> do
    rendered <- traverse renderLevelExpr (Vector.toList levels)
    pure $ do
      values <- sequence rendered
      Right
        (case values of
           [] -> "0"
           level : rest ->
             foldl (\left right -> "(max " <> left <> " " <> right <> ")") level rest
        )
  LevelVariable binder -> do
    binders <- asks renderBinders
    pure
      ( maybe
          (Left ("unbound level binder " <> Text.pack (show binder)))
          Right
          (Map.lookup binder binders)
      )

renderClause :: EmitOptions -> ModuleIR -> CoreClause -> Either Text Text
renderClause options moduleIR clause =
  runRender options moduleIR $ bindClauseTelescope (Vector.toList (clauseTelescope clause))
  where
    bindClauseTelescope [] = do
      renderedPatterns <- traverse renderCorePattern (Vector.toList (clausePatterns clause))
      renderedBody <- renderTerm (clauseBody clause)
      pure $ do
        patterns <- sequence renderedPatterns
        body <- renderedBody
        Right
          ( "| "
              <> (if null patterns then "_" else Text.unwords patterns)
              <> " => "
              <> body
          )
    bindClauseTelescope (binder : rest) =
      local (bindRenderedBinder binder) (bindClauseTelescope rest)

renderCorePattern :: CorePattern -> RenderM (Either Text Text)
renderCorePattern = \case
  PatternVariable binder -> do
    binders <- asks renderBinders
    pure
      ( maybe
          (Left ("unbound pattern binder " <> Text.pack (show binder)))
          Right
          (Map.lookup binder binders)
      )
  PatternConstructor name patterns -> do
    rendered <- traverse renderCorePattern (Vector.toList patterns)
    overrides <- asks renderNameOverrides
    pure $ do
      values <- sequence rendered
      Right (renderPatternApplication (Map.findWithDefault (leanQualifiedName name) name overrides) values)
  PatternBuiltin builtin patterns -> do
    rendered <- traverse renderCorePattern (Vector.toList patterns)
    registry <- asks renderRegistry
    pure $ do
      mapping <-
        maybe
          (Left ("unregistered builtin pattern: " <> Text.pack (show builtin)))
          Right
          (Map.lookup builtin registry)
      values <- sequence rendered
      Right (renderPatternApplication (platformTarget mapping) values)
  PatternLiteral kind value -> pure (Right (renderLiteral kind value))
  PatternWildcard -> pure (Right "_")

renderPatternApplication :: Text -> [Text] -> Text
renderPatternApplication constructor patterns =
  case patterns of
    [] -> constructor
    _ -> "(" <> constructor <> " " <> Text.unwords patterns <> ")"

renderRecordSchema :: EmitOptions -> ModuleIR -> Text -> RecordSchema -> Either Text [Text]
renderRecordSchema options moduleIR recordName schema =
  runRender options moduleIR (renderParameters [] (Vector.toList (recordParameters schema)))
  where
    renderParameters rendered [] = do
      renderFields rendered [] (Vector.toList (recordFields schema))
    renderParameters rendered (binder : rest) = do
      renderedType <- renderTerm (binderType binder)
      case renderedType of
        Left reason -> pure (Left reason)
        Right type' ->
          local
            (bindRenderedBinder binder)
            (renderParameters (rendered <> [renderBinder binder type']) rest)
    renderFields parameters fields [] =
      pure
        ( Right
            ( ("structure " <> recordName <> renderParameterSuffix parameters <> " where")
                : map ("  " <>) fields
            )
        )
    renderFields parameters fields (field : rest) = do
      let binder = recordFieldBinder field
      renderedType <- renderTerm (binderType binder)
      case renderedType of
        Left reason -> pure (Left reason)
        Right type' ->
          local
            (bindRenderedBinder binder)
            ( renderFields
                parameters
                (fields <> [leanNamePart (lastNamePart (recordFieldName field)) <> " : " <> type'])
                rest
            )
    renderParameterSuffix [] = ""
    renderParameterSuffix parameters = " " <> Text.unwords parameters

runRender :: EmitOptions -> ModuleIR -> RenderM (Either Text a) -> Either Text a
runRender options moduleIR action =
  evalState
    ( runReaderT
        action
        RenderEnv
          { renderTerms = moduleTerms moduleIR
          , renderBinders = Map.empty
          , renderRegistry = emitRegistry options
          , renderNameOverrides = moduleNameOverrides moduleIR
          }
    )
    Set.empty

moduleNameOverrides :: ModuleIR -> Map CanonicalName Text
moduleNameOverrides moduleIR =
  Map.fromList (concatMap declarationOverrides (Vector.toList (moduleDeclarations moduleIR)))
  where
    declarationOverrides declaration =
      case declarationDefinition declaration of
        RecordDefinition schema ->
          [ ( recordConstructor schema
            , leanQualifiedName (declarationName declaration) <> ".mk"
            )
          ]
        ProjectionDefinition schema ->
          [ (declarationName declaration, leanQualifiedName (projectionField schema)) ]
        ConstructorDefinition schema ->
          [ ( declarationName declaration
            , leanQualifiedName (constructorOwner schema)
                <> "."
                <> leanNamePart (lastNamePart (declarationName declaration))
            )
          ]
        _ -> []

isPropositionType :: ModuleIR -> TermId -> Bool
isPropositionType moduleIR = go Set.empty
  where
    go seen termId
      | termId `Set.member` seen = False
      | otherwise =
          case Map.lookup termId (moduleTerms moduleIR) of
            Just Equality {} -> True
            Just (Pi _ body) -> go (Set.insert termId seen) body
            _ -> False

renderConstant :: CanonicalName -> Text
renderConstant name =
  case Text.stripPrefix "agda2lean.literal." (unCanonicalName name) of
    Just encoded ->
      let (kind, remainder) = Text.breakOn "." encoded
          value = Text.drop 1 remainder
       in case kind of
            "nat" -> value
            "integer" -> value
            "float" -> value
            "string" -> Text.pack (show value)
            "char" ->
              case Text.uncons value of
                Just (character, _) -> Text.pack (show character)
                Nothing -> "''"
            _ -> leanQualifiedName name
    Nothing -> leanQualifiedName name

renderLiteral :: Text -> Text -> Text
renderLiteral kind value =
  case kind of
    "nat" -> value
    "integer" -> value
    "float" -> value
    "string" -> Text.pack (show value)
    "char" ->
      case Text.uncons value of
        Just (character, _) -> Text.pack (show character)
        Nothing -> "''"
    _ -> leanQualifiedName (CanonicalName ("agda2lean.literal." <> kind <> "." <> value))

parenthesizedApplication :: Text -> [Text] -> Text
parenthesizedApplication function arguments =
  case arguments of
    [] -> function
    _ -> "(@" <> function <> " " <> Text.intercalate " " arguments <> ")"

leanQualifiedName :: CanonicalName -> Text
leanQualifiedName =
  Text.intercalate "." . map leanNamePart . Text.splitOn "." . unCanonicalName

localLeanName :: CanonicalName -> CanonicalName -> Text
localLeanName moduleName' declarationName' =
  case Text.stripPrefix (unCanonicalName moduleName' <> ".") (unCanonicalName declarationName') of
    Just suffix -> Text.intercalate "." (map leanNamePart (Text.splitOn "." suffix))
    Nothing -> leanQualifiedName declarationName'

lastNamePart :: CanonicalName -> Text
lastNamePart =
  lastWithDefault "unnamed" . Text.splitOn "." . unCanonicalName

leanNamePart :: Text -> Text
leanNamePart value
  | validLeanIdentifier value && value `Set.notMember` leanKeywords = value
  | otherwise = "«" <> Text.replace "»" "_u00bb_" value <> "»"

validLeanIdentifier :: Text -> Bool
validLeanIdentifier value =
  case Text.uncons value of
    Nothing -> False
    Just (first, rest) ->
      (isAlpha first || first == '_')
        && Text.all (\character -> isAlphaNum character || character == '_' || character == '\'') rest

leanKeywords :: Set Text
leanKeywords =
  Set.fromList
    [ "axiom", "by", "class", "def", "do", "else", "end", "example"
    , "Level", "Prop"
    , "for", "fun", "if", "import", "in", "inductive", "instance", "let"
    , "match", "namespace", "opaque", "open", "partial", "structure"
    , "syntax", "theorem", "universe", "variable", "where", "with"
    ]

renderDependencies :: Set CanonicalName -> Text
renderDependencies dependencies
  | Set.null dependencies = "(none)"
  | otherwise =
      Text.intercalate ", " (map unCanonicalName (Set.toAscList dependencies))

renderDiagnostics :: Vector.Vector LeanDiagnostic -> Text
renderDiagnostics diagnostics =
  Text.unlines
    ( header
        : map renderDiagnostic
          (sortOn diagnosticSortKey (Vector.toList diagnostics))
    )
  where
    header = "severity\tcode\tdeclaration\tmessage"
    diagnosticSortKey diagnostic =
      ( diagnosticSeverity diagnostic
      , diagnosticCode diagnostic
      , diagnosticDeclaration diagnostic
      )
    renderDiagnostic diagnostic =
      Text.intercalate
        "\t"
        [ Text.pack (show (diagnosticSeverity diagnostic))
        , diagnosticCode diagnostic
        , maybe "-" unCanonicalName (diagnosticDeclaration diagnostic)
        , Text.replace "\n" " " (diagnosticMessage diagnostic)
        ]

renderBuiltinReceipts :: Vector.Vector BuiltinReceipt -> Text
renderBuiltinReceipts receipts =
  Text.unlines
    ( "declaration\tagda-binding\tbuiltin-id\tregistry\trule\tlean-target\tcomputation\targument-policy\taxiom-delta\tstatus"
        : map renderReceipt (Vector.toList receipts)
    )
  where
    renderReceipt receipt =
      Text.intercalate
        "\t"
        [ unCanonicalName (builtinReceiptDeclaration receipt)
        , builtinReceiptAgdaBinding receipt
        , Text.pack (show (builtinReceiptId receipt))
        , builtinReceiptRegistryVersion receipt
        , maybe "-" id (builtinReceiptRule receipt)
        , maybe "-" id (builtinReceiptLeanTarget receipt)
        , maybe "-" (Text.pack . show) (builtinReceiptComputation receipt)
        , maybe "-" (Text.pack . show) (builtinReceiptArgumentPolicy receipt)
        , if Vector.null (builtinReceiptAxiomDelta receipt)
            then "-"
            else Text.intercalate "," (Vector.toList (builtinReceiptAxiomDelta receipt))
        , builtinReceiptStatus receipt
        ]

moduleUniverseNames :: ModuleIR -> Set Text
moduleUniverseNames =
  foldMap
    (Set.fromList . Vector.toList . declarationUniverses)
    . Vector.toList
    . moduleDeclarations

lastWithDefault :: a -> [a] -> a
lastWithDefault fallback values =
  case reverse values of
    value : _ -> value
    [] -> fallback
