{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StrictData #-}

module Agda2Lean.Lean.Emit
  ( DiagnosticSeverity (..)
  , EmitOptions (..)
  , LeanDiagnostic (..)
  , LeanOutput (..)
  , defaultEmitOptions
  , emitLeanModule
  , renderDiagnostics
  ) where

import Agda2Lean.IR
import Control.Monad.Reader
import Control.Monad.State.Strict
import Data.Char (isAlpha, isAlphaNum)
import Data.List (sortOn)
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Set (Set)
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as Text
import qualified Data.Vector as Vector

data EmitOptions = EmitOptions
  { emitNamespace :: Bool
  , emitSorryBodies :: Bool
  }
  deriving stock (Eq, Show)

defaultEmitOptions :: EmitOptions
defaultEmitOptions =
  EmitOptions
    { emitNamespace = True
    , emitSorryBodies = True
    }

data DiagnosticSeverity = Info | Warning | Error
  deriving stock (Bounded, Enum, Eq, Ord, Show)

data LeanDiagnostic = LeanDiagnostic
  { diagnosticSeverity :: DiagnosticSeverity
  , diagnosticCode :: Text
  , diagnosticDeclaration :: Maybe CanonicalName
  , diagnosticMessage :: Text
  }
  deriving stock (Eq, Show)

data LeanOutput = LeanOutput
  { leanSource :: Text
  , leanDiagnostics :: Vector.Vector LeanDiagnostic
  }
  deriving stock (Eq, Show)

data RenderEnv = RenderEnv
  { renderTerms :: Map TermId CoreTerm
  , renderBinders :: Map BinderId Text
  }

type RenderM = ReaderT RenderEnv (State (Set TermId))

emitLeanModule :: EmitOptions -> ModuleIR -> LeanOutput
emitLeanModule options moduleIR =
  LeanOutput
    { leanSource =
        Text.unlines
          ( headerLines
              <> importLines
              <> universeLines
              <> namespaceOpen
              <> concat declarationBlocks
              <> namespaceClose
          )
    , leanDiagnostics = Vector.fromList (concat diagnostics)
    }
  where
    headerLines =
      [ "-- Generated by agda2lean. Edits will be overwritten."
      , "-- Source module: " <> unCanonicalName (moduleName moduleIR)
      , "set_option autoImplicit false"
      , ""
      ]
    importLines =
      [ "import " <> leanQualifiedName imported
      | imported <- Set.toAscList (moduleImports moduleIR)
      ]
        <> ["" | not (Set.null (moduleImports moduleIR))]
    namespaceOpen =
      if emitNamespace options
        then ["namespace " <> leanQualifiedName (moduleName moduleIR), ""]
        else []
    universeLines =
      case Set.toAscList (moduleUniverseNames moduleIR) of
        [] -> []
        names -> ["universe " <> Text.unwords (map leanNamePart names), ""]
    namespaceClose =
      if emitNamespace options
        then ["end " <> leanQualifiedName (moduleName moduleIR)]
        else []
    rendered =
      map
        (emitDeclaration options moduleIR)
        (Vector.toList (moduleDeclarations moduleIR))
    declarationBlocks = map fst rendered
    diagnostics = map snd rendered

emitDeclaration ::
  EmitOptions ->
  ModuleIR ->
  CoreDeclaration ->
  ([Text], [LeanDiagnostic])
emitDeclaration options moduleIR declaration =
  case renderRoot moduleIR (declarationType declaration) of
    Left message ->
      ( metadata
          <> [ "-- BLOCKED: the Agda statement could not be represented faithfully."
             , "-- " <> message
             , ""
             ]
      , [diagnostic Error "A2L-E-TYPE" message]
      )
    Right renderedType ->
      let (bodyLines, bodyDiagnostics) = emitBody renderedType
       in (metadata <> bodyLines <> [""], bodyDiagnostics)
  where
    name = localLeanName (moduleName moduleIR) (declarationName declaration)
    metadata =
      [ "-- Agda: " <> unCanonicalName (declarationName declaration)
      , "-- Source: "
          <> sourceFile (declarationSource declaration)
          <> ":"
          <> Text.pack (show (sourceStartLine (declarationSource declaration)))
      , "-- Direct dependencies: " <> renderDependencies (declarationDependencies declaration)
      , "-- Mapping: " <> Text.pack (show (declarationMapping declaration))
      ]

    diagnostic severity code message =
      LeanDiagnostic
        { diagnosticSeverity = severity
        , diagnosticCode = code
        , diagnosticDeclaration = Just (declarationName declaration)
        , diagnosticMessage = message
        }

    emitBody renderedType =
      case declarationRole declaration of
        AxiomDeclaration ->
          (["axiom " <> name <> " : " <> renderedType], [])
        LogicalProposition ->
          emitValue "def" renderedType
        Theorem ->
          emitTheorem renderedType
        Certificate ->
          emitTheorem renderedType
        _ ->
          emitValue
            (if declarationBody declaration == Nothing then "opaque" else "def")
            renderedType

    emitTheorem renderedType =
      case exactBody of
        Right body ->
          (["theorem " <> name <> " : " <> renderedType <> " := " <> body], [])
        Left reason
          | emitSorryBodies options ->
              ( [ "theorem " <> name <> " : " <> renderedType <> " := by"
                , "  -- agda2lean reconstruction boundary: " <> reason
                , "  sorry"
                ]
              , [diagnostic Warning "A2L-W-RECONSTRUCT" reason]
              )
          | otherwise ->
              ( [ "-- BLOCKED theorem " <> name <> " : " <> renderedType
                , "-- " <> reason
                ]
              , [diagnostic Error "A2L-E-BODY" reason]
              )

    emitValue keyword renderedType =
      case exactBody of
        Right body ->
          ([keyword <> " " <> name <> " : " <> renderedType <> " := " <> body], [])
        Left reason ->
          (["axiom " <> name <> " : " <> renderedType],
           [diagnostic Warning "A2L-W-AXIOM" reason])

    exactBody
      | declarationMapping declaration > Encoded =
          Left
            ( "mapping mode "
                <> Text.pack (show (declarationMapping declaration))
                <> " requires native Lean reconstruction"
            )
      | otherwise =
          case declarationBody declaration of
            Nothing -> Left "Agda did not expose a portable body"
            Just body -> renderRoot moduleIR body

renderRoot :: ModuleIR -> TermId -> Either Text Text
renderRoot moduleIR root =
  evalState
    ( runReaderT
        (renderTerm root)
        RenderEnv
          { renderTerms = moduleTerms moduleIR
          , renderBinders = Map.empty
          }
    )
    Set.empty

renderTerm :: TermId -> RenderM (Either Text Text)
renderTerm termId = do
  active <- get
  if termId `Set.member` active
    then pure (Left ("cyclic term graph at " <> Text.pack (show termId)))
    else do
      table <- asks renderTerms
      case Map.lookup termId table of
        Nothing -> pure (Left ("missing term " <> Text.pack (show termId)))
        Just term -> do
          modify' (Set.insert termId)
          result <- renderCoreTerm term
          modify' (Set.delete termId)
          pure result

renderCoreTerm :: CoreTerm -> RenderM (Either Text Text)
renderCoreTerm = \case
  Var binderId -> do
    binders <- asks renderBinders
    pure
      ( maybe
          (Left ("unbound binder " <> Text.pack (show binderId)))
          Right
          (Map.lookup binderId binders)
      )
  Sort universe -> pure (Right (renderUniverse universe))
  Pi binder body -> renderBinderTerm "→" binder body
  Sigma binder body -> do
    renderedType <- renderTerm (binderType binder)
    renderedBody <- local (bindRenderedBinder binder) (renderTerm body)
    pure $ do
      type' <- renderedType
      body' <- renderedBody
      Right
        ( "Sigma (fun "
            <> leanBinderName binder
            <> " : "
            <> type'
            <> " => "
            <> body'
            <> ")"
        )
  Lam binder body -> do
    renderedType <- renderTerm (binderType binder)
    renderedBody <- local (bindRenderedBinder binder) (renderTerm body)
    pure $ do
      type' <- renderedType
      body' <- renderedBody
      Right
        ( "(fun "
            <> renderBinder binder type'
            <> " => "
            <> body'
            <> ")"
        )
  App function argument -> do
    renderedFunction <- renderTerm function
    renderedArgument <- renderTerm (argumentTerm argument)
    pure $ do
      function' <- renderedFunction
      argument' <- renderedArgument
      Right ("(" <> function' <> " " <> argument' <> ")")
  Constructor name arguments ->
    renderNamedApplication name arguments
  Eliminator name arguments -> do
    rendered <- mapM (renderTerm . argumentTerm) (Vector.toList arguments)
    pure $ do
      values <- sequence rendered
      case values of
        [receiver] -> Right ("(" <> receiver <> ")." <> leanNamePart (lastNamePart name))
        _ -> Right (parenthesizedApplication (leanQualifiedName name) values)
  Equality _ left right -> do
    renderedLeft <- renderTerm left
    renderedRight <- renderTerm right
    pure $ do
      left' <- renderedLeft
      right' <- renderedRight
      Right ("(" <> left' <> " = " <> right' <> ")")
  Axiom name -> pure (Right (renderConstant name))
  Extension extension ->
    pure
      ( Left
          ("extension term requires lowering: " <> Text.pack (show extension))
      )

renderBinderTerm :: Text -> Binder -> TermId -> RenderM (Either Text Text)
renderBinderTerm arrow binder body = do
  renderedType <- renderTerm (binderType binder)
  renderedBody <- local (bindRenderedBinder binder) (renderTerm body)
  pure $ do
    type' <- renderedType
    body' <- renderedBody
    Right
      (renderBinder binder type' <> " " <> arrow <> " " <> body')

renderNamedApplication ::
  CanonicalName ->
  Vector.Vector Argument ->
  RenderM (Either Text Text)
renderNamedApplication name arguments = do
  rendered <- mapM (renderTerm . argumentTerm) (Vector.toList arguments)
  pure $ parenthesizedApplication (leanQualifiedName name) <$> sequence rendered

bindRenderedBinder :: Binder -> RenderEnv -> RenderEnv
bindRenderedBinder binder environment =
  environment
    { renderBinders =
        Map.insert
          (binderId binder)
          (leanBinderName binder)
          (renderBinders environment)
    }

renderBinder :: Binder -> Text -> Text
renderBinder binder type' =
  case binderVisibility binder of
    Explicit -> "(" <> name <> " : " <> type' <> ")"
    Implicit -> "{" <> name <> " : " <> type' <> "}"
    Instance -> "[" <> name <> " : " <> type' <> "]"
  where
    name = leanBinderName binder

leanBinderName :: Binder -> Text
leanBinderName binder =
  let candidate = binderName binder
   in if Text.null candidate || candidate == "_"
        then "x" <> Text.pack (show (unBinderId (binderId binder)))
        else leanNamePart candidate

renderUniverse :: Universe -> Text
renderUniverse = \case
  UZero -> "Type"
  USuc universe -> "(Type (" <> renderLevel universe <> " + 1))"
  UMax universes -> "(Type " <> renderMaxLevel universes <> ")"
  ULevel name -> "(Type " <> leanNamePart name <> ")"
  UProp _ -> "Prop"
  USSet universe -> "(Type " <> renderLevel universe <> ")"

renderLevel :: Universe -> Text
renderLevel = \case
  UZero -> "0"
  USuc universe -> "(" <> renderLevel universe <> " + 1)"
  UMax universes -> renderMaxLevel universes
  ULevel name -> leanNamePart name
  UProp universe -> renderLevel universe
  USSet universe -> renderLevel universe

renderMaxLevel :: Vector.Vector Universe -> Text
renderMaxLevel universes =
  case map renderLevel (Vector.toList universes) of
    [] -> "0"
    level : levels -> foldl (\left right -> "(max " <> left <> " " <> right <> ")") level levels

renderConstant :: CanonicalName -> Text
renderConstant name =
  case Text.stripPrefix "agda2lean.literal." (unCanonicalName name) of
    Just encoded ->
      let (kind, remainder) = Text.breakOn "." encoded
          value = Text.drop 1 remainder
       in case kind of
            "nat" -> value
            "integer" -> value
            "float" -> value
            "string" -> Text.pack (show value)
            "char" ->
              case Text.uncons value of
                Just (character, _) -> Text.pack (show character)
                Nothing -> "''"
            _ -> leanQualifiedName name
    Nothing -> leanQualifiedName name

parenthesizedApplication :: Text -> [Text] -> Text
parenthesizedApplication function arguments =
  case arguments of
    [] -> function
    _ -> "(@" <> function <> " " <> Text.intercalate " " arguments <> ")"

leanQualifiedName :: CanonicalName -> Text
leanQualifiedName =
  Text.intercalate "." . map leanNamePart . Text.splitOn "." . unCanonicalName

localLeanName :: CanonicalName -> CanonicalName -> Text
localLeanName moduleName' declarationName' =
  case Text.stripPrefix (unCanonicalName moduleName' <> ".") (unCanonicalName declarationName') of
    Just suffix -> Text.intercalate "." (map leanNamePart (Text.splitOn "." suffix))
    Nothing -> leanQualifiedName declarationName'

lastNamePart :: CanonicalName -> Text
lastNamePart =
  lastWithDefault "unnamed" . Text.splitOn "." . unCanonicalName

leanNamePart :: Text -> Text
leanNamePart value
  | validLeanIdentifier value && value `Set.notMember` leanKeywords = value
  | otherwise = "«" <> Text.replace "»" "_u00bb_" value <> "»"

validLeanIdentifier :: Text -> Bool
validLeanIdentifier value =
  case Text.uncons value of
    Nothing -> False
    Just (first, rest) ->
      (isAlpha first || first == '_')
        && Text.all (\character -> isAlphaNum character || character == '_' || character == '\'') rest

leanKeywords :: Set Text
leanKeywords =
  Set.fromList
    [ "axiom", "by", "class", "def", "do", "else", "end", "example"
    , "for", "fun", "if", "import", "in", "inductive", "instance", "let"
    , "match", "namespace", "opaque", "open", "partial", "structure"
    , "syntax", "theorem", "universe", "variable", "where", "with"
    ]

renderDependencies :: Set CanonicalName -> Text
renderDependencies dependencies
  | Set.null dependencies = "(none)"
  | otherwise =
      Text.intercalate ", " (map unCanonicalName (Set.toAscList dependencies))

renderDiagnostics :: Vector.Vector LeanDiagnostic -> Text
renderDiagnostics diagnostics =
  Text.unlines
    ( header
        : map renderDiagnostic
          (sortOn diagnosticSortKey (Vector.toList diagnostics))
    )
  where
    header = "severity\tcode\tdeclaration\tmessage"
    diagnosticSortKey diagnostic =
      ( diagnosticSeverity diagnostic
      , diagnosticCode diagnostic
      , diagnosticDeclaration diagnostic
      )
    renderDiagnostic diagnostic =
      Text.intercalate
        "\t"
        [ Text.pack (show (diagnosticSeverity diagnostic))
        , diagnosticCode diagnostic
        , maybe "-" unCanonicalName (diagnosticDeclaration diagnostic)
        , Text.replace "\n" " " (diagnosticMessage diagnostic)
        ]

moduleUniverseNames :: ModuleIR -> Set Text
moduleUniverseNames =
  foldMap
    (Set.fromList . Vector.toList . declarationUniverses)
    . Vector.toList
    . moduleDeclarations

lastWithDefault :: a -> [a] -> a
lastWithDefault fallback values =
  case reverse values of
    value : _ -> value
    [] -> fallback
